spring.data.mongodb:
  database: wishlist

  mongodb:
    host: localhost
    port: 27017
    username: root
    password: password

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /api-docs.html
